language: node_js

node_js:
  - '10'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn --frozen-lockfile

cache:
  directories:
    - node_modules

script:
  - yarn run test
